In [43]:
# creation
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(len(a))

print(np.array([[1,2,3],[4,5,6]], dtype=float))

[[1 2 3]
 [4 5 6]]
(2, 3)
2
8
int64
2
[[1. 2. 3.]
 [4. 5. 6.]]


In [64]:
# read
a = np.array([[1,2,3],[4,5,6]])
print(a[1,1])
print(a[:,1])
print(a[a>2])


5
[2 5]
[3 4 5 6]


In [52]:
# arithmatic operations
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,1,1])
print(a+b)
print(np.add(a,b))
print(a+a)
print(np.add(a,a))


[[2 3 4]
 [5 6 7]]
[[2 3 4]
 [5 6 7]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 2  4  6]
 [ 8 10 12]]


In [53]:
# arithmatic operations
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,1,1])
print(a-b)
print(np.subtract(a,b))
print(a-a)
print(np.subtract(a,a))


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]


In [54]:
# arithmatic operations
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,1,1])
print(a/b)
print(np.divide(a,b))
print(a/a)
print(np.divide(a,a))


[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [55]:
# arithmatic operations
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,1,1])
print(a*b)
print(np.multiply(a,b))
print(a*a)
print(np.multiply(a,a))


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 1  4  9]
 [16 25 36]]


In [56]:
# arithmatic operations
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,1,1])
print(a>b)
print(a>a)
print(a>2)
print(b>2)


[[False  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]]
[[False False  True]
 [ True  True  True]]
[False False False]


In [58]:
# aggregate function
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print(b.sum())
print(a.sum(axis = 1))
print(a.sum())

6
[ 6 15]
21


In [59]:
# aggregate function
a = np.array([[1,12,3],[4,5,6]])
b = np.array([1,2,3])
print(a.max(axis = 1))
print(a.max())
print(b.max())

[12  6]
12
3


In [60]:
# aggregate function
a = np.array([[1,12,3],[4,5,6]])
b = np.array([1,2,3])
print(a.mean(axis = 1))
print(a.mean())
print(b.mean())

[5.33333333 5.        ]
5.166666666666667
2.0


In [61]:
# aggregate function
a = np.array([[1,12,3],[4,5,6]])
b = np.array([1,2,3])
print(a.std(axis = 1))
print(a.std())
print(b.std())

[4.78423336 0.81649658]
3.435921354681384
0.816496580927726


In [ ]:
# help
help(np.zeros)

In [ ]:
# help
np.info(np.abs)

In [ ]:
# help
help(np.sort)

In [ ]:
# sort
a = np.array([[3,7],[9,1],[2,5]])
print(a)
print(np.sort(a, axis = 0) )
print(np.sort(a))


[[3 7]
 [9 1]
 [2 5]]
[[2 1]
 [3 5]
 [9 7]]
[[3 7]
 [1 9]
 [2 5]]


In [ ]:
# sort
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt)
print(a)
print(np.sort(a, order = 'name'))

[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [47]:
# initial placeholder
print(np.zeros([2,3]))
print(np.ones([2,3]))
print(np.eye(3))
print(np.random.random([3,3]))
print(np.empty([2,2]))
print(np.full([3,3],7))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.02728585 0.06723716 0.15869815]
 [0.53451996 0.20000177 0.06411498]
 [0.4135433  0.61717278 0.53595056]]
[[1.89989347e-316 0.00000000e+000]
 [6.90629446e-310 6.90623084e-310]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [71]:
# array manipulation
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.transpose())
print(a)
print(a.reshape([3,2]))
print(a.reshape([6,1]))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [72]:
# array manipulation
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.transpose())
print(a)
print(a.reshape([3,2]))
print(a.reshape([6,1]))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [74]:
# array manipulation
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])

a1 = np.append(a,[10,11])
print(a1)
b1 = np.append(b,[10,11])
print(b1)


[ 1  2  3  4  5  6 10 11]
[ 1  2  3 10 11]


In [88]:
# array manipulation
# insert(arr, obj, values, axis=None)
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])

a1 = np.insert(a,0,0, axis=1)
print(a1)
a1 = np.insert(a,0,0, axis=0)
print(a1)
a1 = np.insert(a,0,[5,5,5], axis=0)
print(a1)
b1 = np.insert(b,1,0)
print(b1)



[[0 1 2 3]
 [0 4 5 6]]
[[0 0 0]
 [1 2 3]
 [4 5 6]]
[[5 5 5]
 [1 2 3]
 [4 5 6]]
[1 0 2 3]


In [95]:
# array manipulation
# delete(arr, obj, axis=None)
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])

a1 = np.delete(a,0, axis=1)
print(a1)
a1 = np.delete(a,0,axis=0)
print(a1)
b1 = np.delete(b,1)
print(b1)

[[2 3]
 [5 6]]
[[4 5 6]]
[1 3]


In [109]:
# array manipulation

a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])

a1 = np.vstack([a,b])
print(a1)
b_1 = np.array([[1,1,1,1,1],[2,2,2,2,2]])
b1 = np.hstack([a,b_1])
print(b1)



[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[1 2 3 1 1 1 1 1]
 [4 5 6 2 2 2 2 2]]


In [106]:
# array manipulation

e = np.full([2,2],7)
f = np.eye(2)

print(e)
print(f)

o = np.hstack([e,f])
print(o)

[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[7. 7. 1. 0.]
 [7. 7. 0. 1.]]
